extern const GeoLayout mario_Left_Hand_Open[];
extern const GeoLayout mario_Right_Hand_Open[];
extern const GeoLayout mario_Right_Hand_Cap[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_mario_Left_Hand_Open[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_mario_Right_Hand_Open[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_mario_Right_Hand_Cap[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_mario_Right_Hand_Cap[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_mario_Right_Hand_Cap[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt1[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_mario_Left_Hand_Open[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_mario_Right_Hand_Open[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_mario_Right_Hand_Cap[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_mario_Right_Hand_Cap[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_mario_Right_Hand_Cap[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt2[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_mario_Left_Hand_Open[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_mario_Right_Hand_Open[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_mario_Right_Hand_Cap[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_mario_Right_Hand_Cap[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_mario_Right_Hand_Cap[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt3[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[];
extern const GeoLayout mario_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[];
extern const GeoLayout mario_geo[];
extern Lights1 mario_pacmaneyes_lights;
extern Lights1 mario_pacmanyellow_lights;
extern Lights1 mario_pacmanmouth_lights;
extern Lights1 mario_pacmanred_lights;
extern Lights1 mario_Metal_lights;
extern Lights1 mario_Buttons_lights;
extern Lights1 mario_pacmanclosed_lights;
extern Lights1 mario_pacmandead_lights;
extern Lights1 mario_pacmanshirt_lights;
extern Lights1 mario_pacmanorange_lights;
extern Lights1 mario_pacmandot_lights;
extern u8 mario_pacmaneyesMS_ia8[];
extern u8 mario_Metal_Shade_rgba16_rgba16[];
extern u8 mario_Metal_Light_rgba16_rgba16[];
extern u8 mario_mario_overalls_button_rgba16_ci8[];
extern u8 mario_mario_overalls_button_rgba16_pal_rgba16[];
extern u8 mario_pacmaneyesclosed_ia8[];
extern u8 mario_pacmaneyesdead_ia8[];
extern u8 mario_pacmanpellet_ci4[];
extern u8 mario_pacmanpellet_pal_rgba16[];
extern u8 mario_pacwing2_ia8[];
extern u8 mario_pacwing1_ia8[];
extern Vtx mario_Head_DL_mesh_layer_5_vtx_0[6];
extern Gfx mario_Head_DL_mesh_layer_5_tri_0[];
extern Vtx mario_Head_DL_mesh_layer_1_vtx_0[14];
extern Gfx mario_Head_DL_mesh_layer_1_tri_0[];
extern Vtx mario_Head_DL_mesh_layer_1_vtx_1[14];
extern Gfx mario_Head_DL_mesh_layer_1_tri_1[];
extern Vtx mario_Head_DL_mesh_layer_1_vtx_2[38];
extern Gfx mario_Head_DL_mesh_layer_1_tri_2[];
extern Vtx mario_Left_Arm_Color_mesh_layer_1_vtx_0[12];
extern Gfx mario_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Forearm_skinned_mesh_layer_1_vtx_0[6];
extern Gfx mario_Left_Forearm_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Forearm_mesh_layer_1_vtx_0[6];
extern Gfx mario_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Forearm_mesh_layer_1_vtx_1[29];
extern Gfx mario_Left_Forearm_mesh_layer_1_tri_1[];
extern Vtx mario_Left_Hand_DL_mesh_layer_1_vtx_0[17];
extern Gfx mario_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_vtx_0[28];
extern Gfx mario_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Arm_Color_mesh_layer_1_vtx_0[12];
extern Gfx mario_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Forearm_skinned_mesh_layer_1_vtx_0[6];
extern Gfx mario_Right_Forearm_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Forearm_mesh_layer_1_vtx_0[6];
extern Gfx mario_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Forearm_mesh_layer_1_vtx_1[29];
extern Gfx mario_Right_Forearm_mesh_layer_1_tri_1[];
extern Vtx mario_Right_Hand_DL_mesh_layer_1_vtx_0[17];
extern Gfx mario_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_vtx_0[28];
extern Gfx mario_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_0[28];
extern Gfx mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Hand_Cap_Switch_Option_PACDOT_mesh_layer_4_vtx_0[4];
extern Gfx mario_Right_Hand_Cap_Switch_Option_PACDOT_mesh_layer_4_tri_0[];
extern Vtx mario_Left_Thigh_Color_mesh_layer_1_vtx_0[12];
extern Gfx mario_Left_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Thigh_Color_mesh_layer_1_vtx_1[12];
extern Gfx mario_Left_Thigh_Color_mesh_layer_1_tri_1[];
extern Vtx mario_Left_Leg_skinned_mesh_layer_1_vtx_0[6];
extern Gfx mario_Left_Leg_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Leg_mesh_layer_1_vtx_0[6];
extern Gfx mario_Left_Leg_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Leg_mesh_layer_1_vtx_1[12];
extern Gfx mario_Left_Leg_mesh_layer_1_tri_1[];
extern Vtx mario_Left_Shoe_skinned_mesh_layer_1_vtx_0[6];
extern Gfx mario_Left_Shoe_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Shoe_mesh_layer_1_vtx_0[6];
extern Gfx mario_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Shoe_mesh_layer_1_vtx_1[26];
extern Gfx mario_Left_Shoe_mesh_layer_1_tri_1[];
extern Vtx mario_Left_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx mario_Left_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx mario_Left_Wing_DL_mesh_layer_4_vtx_1[4];
extern Gfx mario_Left_Wing_DL_mesh_layer_4_tri_1[];
extern Vtx mario_PACBODY_mesh_layer_1_vtx_0[37];
extern Gfx mario_PACBODY_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Thigh_Color_mesh_layer_1_vtx_0[12];
extern Gfx mario_Right_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Thigh_Color_mesh_layer_1_vtx_1[12];
extern Gfx mario_Right_Thigh_Color_mesh_layer_1_tri_1[];
extern Vtx mario_Right_Leg_skinned_mesh_layer_1_vtx_0[6];
extern Gfx mario_Right_Leg_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Leg_mesh_layer_1_vtx_0[6];
extern Gfx mario_Right_Leg_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Leg_mesh_layer_1_vtx_1[12];
extern Gfx mario_Right_Leg_mesh_layer_1_tri_1[];
extern Vtx mario_Right_Shoe_DL_skinned_mesh_layer_1_vtx_0[6];
extern Gfx mario_Right_Shoe_DL_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Shoe_DL_mesh_layer_1_vtx_0[6];
extern Gfx mario_Right_Shoe_DL_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Shoe_DL_mesh_layer_1_vtx_1[26];
extern Gfx mario_Right_Shoe_DL_mesh_layer_1_tri_1[];
extern Vtx mario_Right_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx mario_Right_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx mario_Right_Wing_DL_mesh_layer_4_vtx_1[4];
extern Gfx mario_Right_Wing_DL_mesh_layer_4_tri_1[];
extern Gfx mat_mario_pacmaneyes[];
extern Gfx mat_revert_mario_pacmaneyes[];
extern Gfx mat_mario_pacmanyellow[];
extern Gfx mat_revert_mario_pacmanyellow[];
extern Gfx mat_mario_pacmanmouth[];
extern Gfx mat_revert_mario_pacmanmouth[];
extern Gfx mat_mario_pacmanred[];
extern Gfx mat_revert_mario_pacmanred[];
extern Gfx mat_mario_Metal[];
extern Gfx mat_revert_mario_Metal[];
extern Gfx mat_mario_Buttons[];
extern Gfx mat_revert_mario_Buttons[];
extern Gfx mat_mario_pacmanclosed[];
extern Gfx mat_revert_mario_pacmanclosed[];
extern Gfx mat_mario_pacmandead[];
extern Gfx mat_revert_mario_pacmandead[];
extern Gfx mat_mario_pacmanshirt[];
extern Gfx mat_revert_mario_pacmanshirt[];
extern Gfx mat_mario_pacmanorange[];
extern Gfx mat_revert_mario_pacmanorange[];
extern Gfx mat_mario_pacmandot[];
extern Gfx mat_revert_mario_pacmandot[];
extern Gfx mat_mario_Wing_Tip[];
extern Gfx mat_revert_mario_Wing_Tip[];
extern Gfx mat_mario_Wing_Base[];
extern Gfx mat_revert_mario_Wing_Base[];
extern Gfx mario_Head_DL_mesh_layer_5[];
extern Gfx mario_Head_DL_mesh_layer_5_mat_override_Metal_0[];
extern Gfx mario_Head_DL_mesh_layer_5_mat_override_Buttons_1[];
extern Gfx mario_Head_DL_mesh_layer_5_mat_override_pacmaneyes_2[];
extern Gfx mario_Head_DL_mesh_layer_5_mat_override_pacmanclosed_3[];
extern Gfx mario_Head_DL_mesh_layer_5_mat_override_pacmandead_4[];
extern Gfx mario_Head_DL_mesh_layer_1[];
extern Gfx mario_Head_DL_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Head_DL_mesh_layer_1_mat_override_Buttons_1[];
extern Gfx mario_Head_DL_mesh_layer_1_mat_override_pacmaneyes_2[];
extern Gfx mario_Head_DL_mesh_layer_1_mat_override_pacmanclosed_3[];
extern Gfx mario_Head_DL_mesh_layer_1_mat_override_pacmandead_4[];
extern Gfx mario_Left_Arm_Color_mesh_layer_1[];
extern Gfx mario_Left_Arm_Color_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Left_Forearm_skinned_mesh_layer_1[];
extern Gfx mario_Left_Forearm_skinned_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Left_Forearm_mesh_layer_1[];
extern Gfx mario_Left_Forearm_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Left_Hand_DL_mesh_layer_1[];
extern Gfx mario_Left_Hand_DL_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1[];
extern Gfx mario_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Arm_Color_mesh_layer_1[];
extern Gfx mario_Right_Arm_Color_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Forearm_skinned_mesh_layer_1[];
extern Gfx mario_Right_Forearm_skinned_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Forearm_mesh_layer_1[];
extern Gfx mario_Right_Forearm_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Hand_DL_mesh_layer_1[];
extern Gfx mario_Right_Hand_DL_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1[];
extern Gfx mario_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1[];
extern Gfx mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Hand_Cap_Switch_Option_PACDOT_mesh_layer_4[];
extern Gfx mario_Right_Hand_Cap_Switch_Option_PACDOT_mesh_layer_4_mat_override_Metal_0[];
extern Gfx mario_Left_Thigh_Color_mesh_layer_1[];
extern Gfx mario_Left_Thigh_Color_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Left_Leg_skinned_mesh_layer_1[];
extern Gfx mario_Left_Leg_skinned_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Left_Leg_mesh_layer_1[];
extern Gfx mario_Left_Leg_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Left_Shoe_skinned_mesh_layer_1[];
extern Gfx mario_Left_Shoe_skinned_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Left_Shoe_mesh_layer_1[];
extern Gfx mario_Left_Shoe_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Left_Wing_DL_mesh_layer_4[];
extern Gfx mario_Left_Wing_DL_mesh_layer_4_mat_override_Metal_0[];
extern Gfx mario_PACBODY_mesh_layer_1[];
extern Gfx mario_PACBODY_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Thigh_Color_mesh_layer_1[];
extern Gfx mario_Right_Thigh_Color_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Leg_skinned_mesh_layer_1[];
extern Gfx mario_Right_Leg_skinned_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Leg_mesh_layer_1[];
extern Gfx mario_Right_Leg_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Shoe_DL_skinned_mesh_layer_1[];
extern Gfx mario_Right_Shoe_DL_skinned_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Shoe_DL_mesh_layer_1[];
extern Gfx mario_Right_Shoe_DL_mesh_layer_1_mat_override_Metal_0[];
extern Gfx mario_Right_Wing_DL_mesh_layer_4[];
extern Gfx mario_Right_Wing_DL_mesh_layer_4_mat_override_Metal_0[];
extern Gfx mario_material_revert_render_settings[];
