const GeoLayout pactramp_Opacity_Switch_opt1_Trampoline_Switch_State_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pactramp_Trampoline_Body_mesh_layer_1_mat_override_pactramp2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pactramp_Opacity_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, bhv_trampoline_switch),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pactramp_Trampoline_Body_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, pactramp_Opacity_Switch_opt1_Trampoline_Switch_State_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pactramp_Opacity_Switch_opt0_Trampoline_Switch_State_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pactramp_Trampoline_Body_mesh_layer_1_mat_override_pactramp2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pactramp_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_update_layer_transparency),
			GEO_SWITCH_CASE(2, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_SWITCH_CASE(0, bhv_trampoline_switch),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pactramp_Trampoline_Body_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_BRANCH(1, pactramp_Opacity_Switch_opt0_Trampoline_Switch_State_opt1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, pactramp_Opacity_Switch_opt1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pactramp_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pactramp_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
