const GeoLayout paceffect_2_LoD_Switch_opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 68, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 0, 75, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, paceffect_Left_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Left_Forearm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 24, 0, 0, paceffect_Left_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 22, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Left_Hand_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 0, -75, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, paceffect_Right_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Right_Forearm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 24, 0, 0, paceffect_Right_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 22, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Right_Hand_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
										GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -68, 0, 36, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, paceffect_Left_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Left_Leg_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 25, 0, 0, paceffect_Left_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, -11, -34, 10),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Left_Shoe_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 26, 0, 0, paceffect_Left_Shoe_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_TRANSPARENT, 0, 0, 0, paceffect_PACBODY_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -68, 0, -36, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, paceffect_Right_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Right_Leg_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 25, 0, 0, paceffect_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 11, 34, 10),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Right_Shoe_DL_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 26, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Right_Shoe_DL_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout paceffect_2_LoD_Switch_opt0_Cap_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 68, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 0, 75, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, paceffect_Left_Arm_Color_mesh_layer_1_mat_override_pacmanyellow_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Left_Forearm_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 24, 0, 0, paceffect_Left_Forearm_mesh_layer_1_mat_override_pacmanyellow_0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 22, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Left_Hand_DL_mesh_layer_1_mat_override_pacmanyellow_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 0, -75, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, paceffect_Right_Arm_Color_mesh_layer_1_mat_override_pacmanyellow_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Right_Forearm_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 24, 0, 0, paceffect_Right_Forearm_mesh_layer_1_mat_override_pacmanyellow_0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 22, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Right_Hand_DL_mesh_layer_1_mat_override_pacmanyellow_0),
										GEO_CLOSE_NODE(),
										GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -68, 0, 36, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, paceffect_Left_Thigh_Color_mesh_layer_1_mat_override_pacmanyellow_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Left_Leg_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 25, 0, 0, paceffect_Left_Leg_mesh_layer_1_mat_override_pacmanyellow_0),
						GEO_OPEN_NODE(),
							GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, -11, -34, 10),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Left_Shoe_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 26, 0, 0, paceffect_Left_Shoe_mesh_layer_1_mat_override_pacmanyellow_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_OPAQUE, 0, 0, 0, paceffect_PACBODY_mesh_layer_1_mat_override_pacmanyellow_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -68, 0, -36, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, paceffect_Right_Thigh_Color_mesh_layer_1_mat_override_pacmanyellow_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Right_Leg_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 25, 0, 0, paceffect_Right_Leg_mesh_layer_1_mat_override_pacmanyellow_0),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 11, 34, 10),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Right_Shoe_DL_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 26, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Right_Shoe_DL_mesh_layer_1_mat_override_pacmanyellow_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout paceffect_2_LoD_Switch_opt0_Cap_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 68, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 0, 75, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, paceffect_Left_Arm_Color_mesh_layer_1_mat_override_pacmanyellow_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Left_Forearm_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 24, 0, 0, paceffect_Left_Forearm_mesh_layer_1_mat_override_pacmanyellow_0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 22, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Left_Hand_DL_mesh_layer_1_mat_override_pacmanyellow_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 0, -75, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, paceffect_Right_Arm_Color_mesh_layer_1_mat_override_pacmanyellow_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Right_Forearm_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 24, 0, 0, paceffect_Right_Forearm_mesh_layer_1_mat_override_pacmanyellow_0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 22, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Right_Hand_DL_mesh_layer_1_mat_override_pacmanyellow_0),
										GEO_CLOSE_NODE(),
										GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -68, 0, 36, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, paceffect_Left_Thigh_Color_mesh_layer_1_mat_override_pacmanyellow_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Left_Leg_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 25, 0, 0, paceffect_Left_Leg_mesh_layer_1_mat_override_pacmanyellow_0),
						GEO_OPEN_NODE(),
							GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, -11, -34, 10),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Left_Shoe_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 26, 0, 0, paceffect_Left_Shoe_mesh_layer_1_mat_override_pacmanyellow_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_TRANSPARENT, 0, 0, 0, paceffect_PACBODY_mesh_layer_1_mat_override_pacmanyellow_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -68, 0, -36, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, paceffect_Right_Thigh_Color_mesh_layer_1_mat_override_pacmanyellow_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Right_Leg_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 25, 0, 0, paceffect_Right_Leg_mesh_layer_1_mat_override_pacmanyellow_0),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 11, 34, 10),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Right_Shoe_DL_skinned_mesh_layer_1_mat_override_pacmanyellow_0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 26, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_Right_Shoe_DL_mesh_layer_1_mat_override_pacmanyellow_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout paceffect_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 68, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 0, 75, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, paceffect_Left_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Left_Forearm_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 24, 0, 0, paceffect_Left_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 22, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(1, geo_mario_hand_foot_scaler),
																GEO_SCALE(LAYER_FORCE, 65536),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Left_Hand_DL_mesh_layer_1),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 0, -75, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, paceffect_Right_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Right_Forearm_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 24, 0, 0, paceffect_Right_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 22, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(0, geo_mario_hand_foot_scaler),
																GEO_SCALE(LAYER_FORCE, 65536),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Right_Hand_DL_mesh_layer_1),
																GEO_CLOSE_NODE(),
																GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -68, 0, 36, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, paceffect_Left_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Left_Leg_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 25, 0, 0, paceffect_Left_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, -11, -34, 10),
													GEO_OPEN_NODE(),
													GEO_CLOSE_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Left_Shoe_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 26, 0, 0, paceffect_Left_Shoe_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_OPAQUE, 0, 0, 0, paceffect_PACBODY_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -68, 0, -36, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, paceffect_Right_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Right_Leg_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 25, 0, 0, paceffect_Right_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, 11, 34, 10),
													GEO_OPEN_NODE(),
													GEO_CLOSE_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Right_Shoe_DL_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 26, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_Right_Shoe_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, paceffect_2_LoD_Switch_opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, paceffect_2_LoD_Switch_opt0_Cap_State_Switch_opt2),
							GEO_BRANCH(1, paceffect_2_LoD_Switch_opt0_Cap_State_Switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, paceffect_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, paceffect_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
